[project]
name = "agentcore-first-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sagar1208", email = "60442468+sagar1208@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "groq>=0.4.0",
    "bedrock-agentcore>=1.0.0",
    "python-dotenv>=1.2.3",
]

[tool.uv]
package = false
